/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proyectoseguridad;

import javax.swing.*;
import java.io.File;
import java.io.IOException;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.security.spec.InvalidKeySpecException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.Cipher;
import javax.crypto.NoSuchPaddingException;
import org.apache.commons.io.FilenameUtils;

/**
 *
 * @author eugen
 */
public class Archivos extends javax.swing.JFrame {

    EncodeDecode encriptararchivo = new EncodeDecode();
    Limpiar limpiacampos = new Limpiar();
    JFileChooser seleccionarArchivo;
    JFileChooser seleccionarCarpeta;
    String nombrearchivo = "";
    String carpeta = "";
    String filename = "";
    String namefinal = "";
    String namefinaldecrypted = "";

    public Archivos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filewindow = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_cargarfile = new javax.swing.JButton();
        patharchivo = new javax.swing.JTextField();
        btn_encodefile = new javax.swing.JButton();
        btn_decodefile = new javax.swing.JButton();
        btn_loadkey = new javax.swing.JButton();
        btn_diroutput = new javax.swing.JButton();
        directorio = new javax.swing.JTextField();
        keypass = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btn_limpiar = new javax.swing.JButton();
        Barra_color = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Roboto Slab ExtraBold", 1, 18)); // NOI18N
        jLabel1.setText("Encriptacion y Desencriptacion de Archivos");

        btn_cargarfile.setBackground(new java.awt.Color(0, 153, 153));
        btn_cargarfile.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        btn_cargarfile.setText("Cargar Archivo");
        btn_cargarfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cargarfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cargarfileActionPerformed(evt);
            }
        });

        patharchivo.setFont(new java.awt.Font("Roboto Slab Light", 0, 12)); // NOI18N

        btn_encodefile.setBackground(new java.awt.Color(0, 153, 153));
        btn_encodefile.setFont(new java.awt.Font("Roboto Slab Medium", 0, 12)); // NOI18N
        btn_encodefile.setText("Encriptar Archivo");
        btn_encodefile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_encodefile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_encodefileActionPerformed(evt);
            }
        });

        btn_decodefile.setBackground(new java.awt.Color(0, 153, 153));
        btn_decodefile.setFont(new java.awt.Font("Roboto Slab Medium", 0, 12)); // NOI18N
        btn_decodefile.setText("Desencriptar Archivo");
        btn_decodefile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_decodefile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_decodefileActionPerformed(evt);
            }
        });

        btn_loadkey.setBackground(new java.awt.Color(0, 153, 153));
        btn_loadkey.setFont(new java.awt.Font("Roboto Slab Medium", 0, 12)); // NOI18N
        btn_loadkey.setText("Cargar Llave");
        btn_loadkey.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_loadkey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loadkeyActionPerformed(evt);
            }
        });

        btn_diroutput.setBackground(new java.awt.Color(0, 153, 153));
        btn_diroutput.setFont(new java.awt.Font("Roboto Slab Medium", 0, 12)); // NOI18N
        btn_diroutput.setText("Directorio de Sálida");
        btn_diroutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_diroutputActionPerformed(evt);
            }
        });

        directorio.setFont(new java.awt.Font("Roboto Slab Light", 0, 12)); // NOI18N

        keypass.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        keypass.setText("Ingresa una llave");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        btn_limpiar.setBackground(new java.awt.Color(0, 153, 153));
        btn_limpiar.setFont(new java.awt.Font("Roboto Slab Medium", 0, 12)); // NOI18N
        btn_limpiar.setText("Limpiar");
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout filewindowLayout = new javax.swing.GroupLayout(filewindow);
        filewindow.setLayout(filewindowLayout);
        filewindowLayout.setHorizontalGroup(
            filewindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filewindowLayout.createSequentialGroup()
                .addGroup(filewindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(filewindowLayout.createSequentialGroup()
                        .addGroup(filewindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(filewindowLayout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(jLabel1))
                            .addGroup(filewindowLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(filewindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, filewindowLayout.createSequentialGroup()
                                        .addComponent(btn_decodefile)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(16, 16, 16))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, filewindowLayout.createSequentialGroup()
                                        .addComponent(btn_diroutput)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(directorio, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(filewindowLayout.createSequentialGroup()
                                        .addGroup(filewindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn_loadkey)
                                            .addComponent(btn_cargarfile))
                                        .addGap(35, 35, 35)
                                        .addGroup(filewindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(keypass, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(patharchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(filewindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_encodefile)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        filewindowLayout.setVerticalGroup(
            filewindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filewindowLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(filewindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cargarfile)
                    .addComponent(patharchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(filewindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keypass, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_loadkey))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(filewindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_diroutput)
                    .addComponent(directorio, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_encodefile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(filewindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_decodefile)
                    .addComponent(btn_limpiar))
                .addGap(51, 51, 51))
        );

        Barra_color.setBackground(new java.awt.Color(0, 153, 153));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imageedit_3_2315935325.png"))); // NOI18N

        javax.swing.GroupLayout Barra_colorLayout = new javax.swing.GroupLayout(Barra_color);
        Barra_color.setLayout(Barra_colorLayout);
        Barra_colorLayout.setHorizontalGroup(
            Barra_colorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Barra_colorLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        Barra_colorLayout.setVerticalGroup(
            Barra_colorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Barra_colorLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(filewindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Barra_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(filewindow, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(Barra_color, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
String contrasena;
    private void btn_cargarfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cargarfileActionPerformed

        seleccionarArchivo = new JFileChooser();
        seleccionarArchivo.showOpenDialog(null);
        nombrearchivo = seleccionarArchivo.getSelectedFile().getAbsolutePath();
        patharchivo.setText(nombrearchivo);
        filename = FilenameUtils.removeExtension(seleccionarArchivo.getSelectedFile().getName());
        namefinal = "//" + filename + ".encrypted";
        namefinaldecrypted = "//" + filename + "_desencriptado";
    }//GEN-LAST:event_btn_cargarfileActionPerformed

    private void btn_encodefileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_encodefileActionPerformed

        File plano = new File(seleccionarArchivo.getSelectedFile().getAbsolutePath());

       
        File encriptado = new File(carpeta + namefinal);
        try {
            encriptararchivo.proc(contrasena, Cipher.ENCRYPT_MODE, plano, encriptado);
            JOptionPane.showMessageDialog(null, "Archivo Encriptado");
        } catch (InvalidKeyException ex) {
            Logger.getLogger(Archivos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(Archivos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InvalidKeySpecException ex) {
            Logger.getLogger(Archivos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchPaddingException ex) {
            Logger.getLogger(Archivos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Archivos.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btn_encodefileActionPerformed

    private void btn_loadkeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loadkeyActionPerformed
        // TODO add your handling code here:
        contrasena = keypass.getText();
    }//GEN-LAST:event_btn_loadkeyActionPerformed

    private void btn_decodefileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_decodefileActionPerformed
        
        File encriptado = new File(carpeta + namefinal);
        String extension = "";
        int i = nombrearchivo.lastIndexOf('.');
        if (i > 0) {
            extension = nombrearchivo.substring(i + 1);
        }

        File desencriptado = new File(carpeta + namefinaldecrypted +"." + extension);
        try {
            encriptararchivo.proc(contrasena, Cipher.DECRYPT_MODE, encriptado, desencriptado);
            JOptionPane.showMessageDialog(null, "Archivo Desencriptado");
        } catch (InvalidKeyException ex) {
            Logger.getLogger(Archivos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(Archivos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InvalidKeySpecException ex) {
            Logger.getLogger(Archivos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NoSuchPaddingException ex) {
            Logger.getLogger(Archivos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Archivos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_decodefileActionPerformed

    private void btn_diroutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_diroutputActionPerformed
        seleccionarCarpeta = new JFileChooser();
        seleccionarCarpeta.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        seleccionarCarpeta.showOpenDialog(null);
        carpeta = seleccionarCarpeta.getSelectedFile().getAbsolutePath();
        directorio.setText(carpeta);


    }//GEN-LAST:event_btn_diroutputActionPerformed

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        limpiacampos.limpiar(filewindow);
    }//GEN-LAST:event_btn_limpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Archivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Archivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Archivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Archivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Archivos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Barra_color;
    private javax.swing.JButton btn_cargarfile;
    private javax.swing.JButton btn_decodefile;
    private javax.swing.JButton btn_diroutput;
    private javax.swing.JButton btn_encodefile;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton btn_loadkey;
    private javax.swing.JTextField directorio;
    private javax.swing.JPanel filewindow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField keypass;
    private javax.swing.JTextField patharchivo;
    // End of variables declaration//GEN-END:variables
}
